I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "game/custom/variables.rpy", line 92, in execute_default
    default KitchenFirstVisit = True
Exception: store.KitchenFirstVisit is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\exports.py", line 3972, in execute_default_statement
    i.execute_default(start)
  File "game/custom/variables.rpy", line 92, in execute_default
    default KitchenFirstVisit = True
Exception: store.KitchenFirstVisit is being given a default a second time.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.1.23060707
ProjectCW 1.0
Wed Feb 21 16:42:23 2024
